name: Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout date
      uses: moonrailgun/branch-filestorage-action@v1.0.0
      with:
        path: date
    - name: Read and show
      run: cat date
    - name: update date
      run: echo $(date) > date
